### ISSUE TITLE
weird behaviour with language files

### ISSUE THREAD

**Issue by AlphaRalph** [AeonSake/CustomerManager#9] opened 2018-05-04 08:53 UTC
when changing existing language files, after restart changed versions are not visible any longer, neither unchanged ones.

**Comment by AeonSake** [comment] 2018-05-04 10:32
This problem was caused by Windows' UAC virtualization due to a `File.ReadAllText()` call. This method opens, reads and closes the file. The process of opening a file located in program files caused Windows to emulate a virtual environment for the application since it doesn't allow editing files in the program file directory without admin privileges.
The bug was fixed by moving dynamic files to the local appdata folder.

**Closed by AeonSake** 2018-05-04 10:32 UTC
Labels: bug
